// ── PDF generation (jsPDF + autotable) ──────────────────────
// This module is ALWAYS loaded via dynamic import — keep it out of the
// main bundle. Callers: InvoicesTab, GlobalPages, Reports, TenantPages.
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice, Payment, Property, Tenant, Lease, CompanyProfile } from '../types';
import { formatDate, formatMonthYear } from './index';

// ── SA flag palette (exact official colours) ────────────────
const GREEN: [number, number, number] = [0, 119, 73];    // #007749
const GOLD:  [number, number, number] = [255, 184, 28];  // #FFB81C
const RED:   [number, number, number] = [224, 60, 49];   // #E03C31
const INK:   [number, number, number] = [23, 28, 25];
const MUTED: [number, number, number] = [109, 117, 110];
const LIGHT: [number, number, number] = [233, 247, 240];

// jsPDF's built-in fonts are WinAnsi — keep output strictly ASCII.
// (toLocaleString('en-ZA') inserts U+202F separators that render as garbage.)
const money = (n: number): string => {
  const sign = n < 0 ? '-' : '';
  const [int, dec] = Math.abs(n).toFixed(2).split('.');
  return `${sign}R ${int.replace(/\B(?=(\d{3})+(?!\d))/g, ' ')}.${dec}`;
};

const PAGE_W = 210; // A4 portrait, mm
const MARGIN = 16;

function header(doc: jsPDF, docTitle: string, subtitle: string, company?: CompanyProfile | null) {
  // Green masthead with gold keyline — SA flag colours. The landlord's
  // company name (when set) brands the document; otherwise it falls back
  // to the PropMaster wordmark.
  const brand = company?.companyName?.trim() || 'PropMaster';
  const tagline = company?.companyName?.trim()
    ? 'Property management · South Africa'
    : 'Property management for South African landlords';

  doc.setFillColor(...GREEN);
  doc.rect(0, 0, PAGE_W, 26, 'F');
  doc.setFillColor(...GOLD);
  doc.rect(0, 26, PAGE_W, 1.6, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(brand.length > 30 ? 13 : 16);
  doc.text(brand, MARGIN, 12, { maxWidth: PAGE_W / 2 });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text(tagline, MARGIN, 18);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(docTitle, PAGE_W - MARGIN, 12, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(subtitle, PAGE_W - MARGIN, 18, { align: 'right' });
}

function footer(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    const h = doc.internal.pageSize.getHeight();
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.5);
    doc.line(MARGIN, h - 12, PAGE_W - MARGIN, h - 12);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(`Generated by PropMaster on ${formatDate(new Date().toISOString().split('T')[0])}`, MARGIN, h - 7);
    doc.text(`Page ${i} of ${pages}`, PAGE_W - MARGIN, h - 7, { align: 'right' });
  }
}

// ── Invoice ─────────────────────────────────────────────────
export interface InvoicePdfInput {
  invoice: Invoice;
  property?: Property | null;
  tenant?: Tenant | null;
  lease?: Lease | null;
  /** Verified payments linked to this invoice. */
  payments: Payment[];
  /** Issuing landlord's business identity (masthead + "From" block). */
  company?: CompanyProfile | null;
}

export function downloadInvoicePdf({ invoice, property, tenant, lease, payments, company }: InvoicePdfInput) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  // A VAT-registered issuer produces a "TAX INVOICE" (SA convention).
  const title = company?.vatNumber?.trim() ? 'TAX INVOICE' : 'INVOICE';
  header(doc, title, invoice.invoiceNumber, company);

  let y = 38;
  const colR = PAGE_W / 2 + 4;

  // From (issuer) — left · Bill To (tenant) — right
  doc.setTextColor(...MUTED);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('FROM', MARGIN, y);
  doc.text('BILL TO', colR, y);

  doc.setFontSize(9.5);
  doc.setTextColor(...INK);

  // Issuer block
  const fromLines: { t: string; bold?: boolean }[] = [];
  fromLines.push({ t: company?.companyName?.trim() || 'PropMaster', bold: true });
  if (company?.companyAddress?.trim()) {
    company.companyAddress.split('\n').forEach(l => fromLines.push({ t: l }));
  }
  if (company?.companyEmail?.trim()) fromLines.push({ t: company.companyEmail });
  if (company?.companyPhone?.trim()) fromLines.push({ t: company.companyPhone });
  if (company?.vatNumber?.trim()) fromLines.push({ t: `VAT No: ${company.vatNumber}` });
  if (company?.registrationNumber?.trim()) fromLines.push({ t: `Reg No: ${company.registrationNumber}` });

  fromLines.forEach((l, i) => {
    doc.setFont('helvetica', l.bold ? 'bold' : 'normal');
    doc.text(l.t, MARGIN, y + 6 + i * 5, { maxWidth: PAGE_W / 2 - MARGIN - 4 });
  });

  // Bill-to block
  const billLines: { t: string; bold?: boolean }[] = [];
  billLines.push({ t: tenant?.name || 'Tenant', bold: true });
  if (tenant?.email) billLines.push({ t: tenant.email });
  if (tenant?.phone) billLines.push({ t: tenant.phone });
  if (property) {
    billLines.push({ t: '' });
    billLines.push({ t: property.name + (property.unitNumber ? ` (Unit ${property.unitNumber})` : '') });
    billLines.push({ t: property.address });
    billLines.push({ t: `${property.city}, ${property.province}` });
  }
  billLines.forEach((l, i) => {
    doc.setFont('helvetica', l.bold ? 'bold' : 'normal');
    doc.text(l.t, colR, y + 6 + i * 5, { maxWidth: PAGE_W - colR - MARGIN });
  });

  y += 6 + Math.max(fromLines.length, billLines.length) * 5 + 4;

  // Meta strip — period / due / status
  doc.setDrawColor(...LIGHT);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(
    `Billing period: ${formatMonthYear(invoice.month, invoice.year)}     Due: ${formatDate(invoice.dueDate)}     Status: ${invoice.status.toUpperCase()}`,
    MARGIN, y,
  );
  y += 6;

  // Line items
  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [['Description', 'Amount']],
    body: invoice.lineItems.map(li => [li.description, money(li.amount)]),
    styles: { font: 'helvetica', fontSize: 9.5, textColor: INK, cellPadding: 2.6 },
    headStyles: { fillColor: GREEN, textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [250, 252, 250] },
    columnStyles: { 1: { halign: 'right', cellWidth: 40 } },
  });

  y = (doc as any).lastAutoTable.finalY + 4;

  // Totals block
  const totalPaid = payments.reduce((s, p) => s + p.amount, 0);
  const balance = invoice.totalAmount - totalPaid;

  const totalsRows: [string, string][] = [['Invoice total', money(invoice.totalAmount)]];
  if (totalPaid > 0) {
    totalsRows.push(['Paid to date', money(-totalPaid)]);
    totalsRows.push([balance > 0 ? 'Balance due' : 'Balance', money(Math.max(balance, 0))]);
  }

  const boxW = 78;
  const boxX = PAGE_W - MARGIN - boxW;
  totalsRows.forEach(([label, value], i) => {
    const isLast = i === totalsRows.length - 1;
    const rowY = y + i * 8;
    if (isLast) {
      doc.setFillColor(...(balance > 0 && totalPaid > 0 ? RED : GREEN));
      doc.rect(boxX, rowY - 5.2, boxW, 8, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
    } else {
      doc.setTextColor(...INK);
      doc.setFont('helvetica', 'normal');
    }
    doc.setFontSize(10);
    doc.text(label, boxX + 3, rowY);
    doc.text(value, boxX + boxW - 3, rowY, { align: 'right' });
  });

  y += totalsRows.length * 8 + 8;

  // Payments received
  if (payments.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text('PAYMENTS RECEIVED', MARGIN, y);
    autoTable(doc, {
      startY: y + 2,
      margin: { left: MARGIN, right: MARGIN },
      head: [['Date', 'Method', 'Reference', 'Amount']],
      body: payments.map(p => [
        formatDate(p.paymentDate),
        (p.method || '').replace(/_/g, ' ').toUpperCase(),
        p.notes || '-',
        money(p.amount),
      ]),
      styles: { font: 'helvetica', fontSize: 9, textColor: INK, cellPadding: 2.2 },
      headStyles: { fillColor: LIGHT, textColor: GREEN, fontStyle: 'bold' },
      columnStyles: { 3: { halign: 'right', cellWidth: 36 } },
    });
  }

  footer(doc);
  doc.save(`${invoice.invoiceNumber}.pdf`);
}

// ── Reports: shared table renderer ──────────────────────────
interface ReportPdfInput {
  docTitle: string;
  subtitle: string;
  fileName: string;
  head: string[];
  body: (string | number)[][];
  /** Bold summary row appended at the end (e.g. totals). */
  foot?: (string | number)[];
  /** Column indexes to right-align (money columns). */
  rightCols?: number[];
  /** Optional stat lines rendered above the table. */
  stats?: [string, string][];
  /** Issuing landlord's business identity for the masthead. */
  company?: CompanyProfile | null;
}

function reportPdf({ docTitle, subtitle, fileName, head, body, foot, rightCols = [], stats, company }: ReportPdfInput) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  header(doc, docTitle, subtitle, company);

  let y = 36;

  if (stats && stats.length > 0) {
    const colW = (PAGE_W - MARGIN * 2) / stats.length;
    stats.forEach(([label, value], i) => {
      const x = MARGIN + i * colW;
      doc.setFillColor(...LIGHT);
      doc.roundedRect(x, y, colW - 3, 14, 1.5, 1.5, 'F');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(...MUTED);
      doc.text(label.toUpperCase(), x + 3, y + 5);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(...GREEN);
      doc.text(value, x + 3, y + 11);
    });
    y += 20;
  }

  const columnStyles: Record<number, { halign: 'right' }> = {};
  rightCols.forEach(i => { columnStyles[i] = { halign: 'right' }; });

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [head],
    body: body.map(row => row.map(String)),
    foot: foot ? [foot.map(String)] : undefined,
    styles: { font: 'helvetica', fontSize: 8.5, textColor: INK, cellPadding: 2.2 },
    headStyles: { fillColor: GREEN, textColor: [255, 255, 255], fontStyle: 'bold' },
    footStyles: { fillColor: [240, 244, 241], textColor: INK, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [250, 252, 250] },
    columnStyles,
  });

  footer(doc);
  doc.save(fileName);
}

// ── Profit & Loss ───────────────────────────────────────────
export interface PnlPdfRow {
  propertyName: string;
  collected: number;
  passthrough: number;
  ownCosts: number;
  net: number;
  paymentCount: number;
}

export function downloadPnlPdf(period: string, rows: PnlPdfRow[], totals: { collected: number; passthrough: number; nonRecoverable: number; net: number }, company?: CompanyProfile | null) {
  reportPdf({
    company,
    docTitle: 'PROFIT & LOSS',
    subtitle: period,
    fileName: `propmaster-pnl-${period.replace(/[^\w-]+/g, '-').toLowerCase()}.pdf`,
    stats: [
      ['Total collected', money(totals.collected)],
      ['Utility pass-through', money(totals.passthrough)],
      ['Own costs', money(totals.nonRecoverable)],
      ['Net profit', money(totals.net)],
    ],
    head: ['Property', 'Collected', 'Utilities to municipality', 'Own costs', 'Net profit', 'Payments'],
    body: rows.map(r => [
      r.propertyName, money(r.collected), money(r.passthrough), money(r.ownCosts), money(r.net), r.paymentCount,
    ]),
    foot: ['TOTAL', money(totals.collected), money(totals.passthrough), money(totals.nonRecoverable), money(totals.net), ''],
    rightCols: [1, 2, 3, 4, 5],
  });
}

// ── Rent Roll ───────────────────────────────────────────────
export interface RentRollPdfRow {
  propertyName: string;
  city: string;
  tenantName: string;
  rent: number | null;
  deposit: number | null;
  leasePeriod: string;
  outstanding: number;
  status: string;
}

export function downloadRentRollPdf(rows: RentRollPdfRow[], totals: { rent: number; deposits: number; outstanding: number; occupancy: string }, company?: CompanyProfile | null) {
  reportPdf({
    company,
    docTitle: 'RENT ROLL',
    subtitle: formatDate(new Date().toISOString().split('T')[0]),
    fileName: `propmaster-rent-roll-${new Date().toISOString().split('T')[0]}.pdf`,
    stats: [
      ['Occupancy', totals.occupancy],
      ['Monthly rent roll', money(totals.rent)],
      ['Deposits held', money(totals.deposits)],
      ['Outstanding', money(totals.outstanding)],
    ],
    head: ['Property', 'Tenant', 'Rent / mo', 'Deposit', 'Lease period', 'Outstanding', 'Status'],
    body: rows.map(r => [
      `${r.propertyName}\n${r.city}`,
      r.tenantName,
      r.rent != null ? money(r.rent) : '-',
      r.deposit != null ? money(r.deposit) : '-',
      r.leasePeriod,
      r.outstanding > 0 ? money(r.outstanding) : '-',
      r.status,
    ]),
    foot: ['TOTALS', '', money(totals.rent), money(totals.deposits), '', money(totals.outstanding), ''],
    rightCols: [2, 3, 5],
  });
}

// ── Outstanding invoices ────────────────────────────────────
export interface OutstandingPdfRow {
  invoiceNumber: string;
  propertyName: string;
  tenantName: string;
  period: string;
  dueDate: string;
  amount: number;
  balance: number;
  status: string;
  daysOverdue: number;
}

export function downloadOutstandingPdf(rows: OutstandingPdfRow[], totals: { overdue: number; sent: number; draft: number; total: number }, company?: CompanyProfile | null) {
  reportPdf({
    company,
    docTitle: 'OUTSTANDING INVOICES',
    subtitle: formatDate(new Date().toISOString().split('T')[0]),
    fileName: `propmaster-outstanding-${new Date().toISOString().split('T')[0]}.pdf`,
    stats: [
      ['Overdue', money(totals.overdue)],
      ['Awaiting payment', money(totals.sent)],
      ['Draft', money(totals.draft)],
      ['Total outstanding', money(totals.total)],
    ],
    head: ['Invoice', 'Property', 'Tenant', 'Period', 'Due date', 'Balance due', 'Status'],
    body: rows.map(r => [
      r.invoiceNumber,
      r.propertyName,
      r.tenantName,
      r.period,
      r.daysOverdue > 0 ? `${r.dueDate}\n(${r.daysOverdue}d overdue)` : r.dueDate,
      money(r.balance),
      r.status.toUpperCase(),
    ]),
    foot: ['TOTAL', '', '', '', '', money(totals.total), ''],
    rightCols: [5],
  });
}
